version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"  # Puerto MQTT
      - "8083:8083"  # WebSockets MQTT
      - "18083:18083" # Dashboard web de EMQX
    environment:
      - EMQX_NAME=emqx
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_LISTENER__WS__EXTERNAL=8083
      - EMQX_DASHBOARD__LISTENER__HTTP=18083
      - EMQX_AUTH__USER__1__USERNAME=user1
      - EMQX_AUTH__USER__1__PASSWORD=clave123
      - EMQX_DEFAULT_LOG_HANDLER= file
      - EMQX_LOG_DIR=/opt/emqx/log
      - EMQX_DATA_DIR=/opt/emqx/data
      
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
