{
 "title": "Dashboard 17f2306e",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Acelerometro UUID: 17f2306e",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/17f2306e/10DOF\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_acelerometro_x\" or r[\"_field\"] == \"data_acelerometro_y\" or r[\"_field\"] == \"data_acelerometro_z\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "Giroscopio UUID: 17f2306e",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/17f2306e/10DOF\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_giroscopio_x\" or r[\"_field\"] == \"data_giroscopio_y\" or r[\"_field\"] == \"data_giroscopio_z\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "Magnetometro UUID: 17f2306e",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/17f2306e/10DOF\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_magnetometro_x\" or r[\"_field\"] == \"data_magnetometro_y\" or r[\"_field\"] == \"data_magnetometro_z\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "Presion UUID: 17f2306e",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 30, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                from(bucket: \"datos\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"topic\"] == \"Si/17f2306e/10DOF\")\n                |> filter(fn: (r) => r[\"_field\"] == \"data_presion\")\n                |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                |> yield(name: \"mean\")\n                "
    }
   ]
  }
 ]
}