{
 "title": "Dashboard 2e90a032",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Accelerometer (IMU) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/IMU\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_accelerometer_x\" or r[\"_field\"] == \"data_accelerometer_y\" or r[\"_field\"] == \"data_accelerometer_z\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "Gyroscope (IMU) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/IMU\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_gyroscope_x\" or r[\"_field\"] == \"data_gyroscope_y\" or r[\"_field\"] == \"data_gyroscope_z\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "Magnetometer (IMU) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/IMU\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_magnetometer_x\" or r[\"_field\"] == \"data_magnetometer_y\" or r[\"_field\"] == \"data_magnetometer_z\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "Quaternion (IMU) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 30, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/IMU\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_quaternion_w\" or r[\"_field\"] == \"data_quaternion_x\" or r[\"_field\"] == \"data_quaternion_y\" or r[\"_field\"] == \"data_quaternion_z\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "latitud (GPS) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 40, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/GPS\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_latitud\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "longitud (GPS) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 50, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/GPS\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_longitud\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "altitud (GPS) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 60, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/GPS\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_altitud\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "speed (GPS) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 70, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/GPS\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_speed\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "satellites (GPS) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 80, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/GPS\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_satellites\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "hdop (GPS) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 90, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/GPS\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_hdop\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "temperature (ENV) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 100, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/ENV\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_temperature\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "pressure (ENV) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 110, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/ENV\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_pressure\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  },
  {
   "title": "humidity (ENV) - UUID: 2e90a032",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 120, "w": 24, "h": 9 },
   "targets": [
    {
     "query": "\n                    from(bucket: \"datos\")\n                    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                    |> filter(fn: (r) => r[\"topic\"] == \"Si/2e90a032/ENV\")\n                    |> filter(fn: (r) => r[\"_field\"] == \"data_humidity\")\n                    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n                    |> yield(name: \"mean\")\n                    "
    }
   ]
  }
 ]
}