services:
  api:
    build: .
    container_name: "api"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PYTHONPATH=/app
    group_add:
      - "docker"
    command: ./start.sh